name: Run checks

on:
  push:
    branches:
      - xavi

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: npm i --legacy-peer-deps
      - name: Run test
        run: npm test
      - name: Build application
        run: npm run build
